<a href="https://colab.research.google.com/github/eildes06/pythonstudies/blob/main/numpymediumcal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
# python list
python_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
# numpy array
numpy_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Python listesi :")
print(python_list)
print("Numpy dizisi :")
print(numpy_array)
#Output:
#Python listesi :
#[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
#Numpy dizisi :
#[0 1 2 3 4 5 6 7 8 9]

Python listesi :
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Numpy dizisi :
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
numpy_array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array1.ndim)

1


In [ ]:
numpy_array2 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
print(numpy_array2.ndim)

2


In [ ]:
numpy_array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array1.shape)
print(numpy_array1.ndim)
#10 tane elemandan oluşan 1 boyutlu bir dizi(vektör).

(10,)
1


In [ ]:
numpy_array2 = np.array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
print(numpy_array2.ndim)
print(numpy_array2.shape)
# 1 satır ve 10 sütundan oluşan 2 boyutlu bir dizi(matris).

2
(1, 10)


In [ ]:
numpy_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array.reshape(1,10))

[[0 1 2 3 4 5 6 7 8 9]]


In [ ]:
print(numpy_array.reshape(10,1))

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


In [ ]:
print(numpy_array.reshape(5,2))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
print(numpy_array.reshape(2,5))

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [ ]:
np.arange(3)

array([0, 1, 2])

In [ ]:
numpy_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
print(numpy_array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#Dizinin herhangi bir satırını seçmek
#1.satır
first_row = numpy_array[0]
#1. ve 2. satır 
first_and_second_rows = numpy_array[0:2]
print(first_row)
print(first_and_second_rows)

[0 1]
[[0 1]
 [2 3]]


In [ ]:
first_and_second_rows = numpy_array[:-3]
#print(first_row)
print(first_and_second_rows)

[[0 1]
 [2 3]]


In [ ]:
#1. sütun
first_column = numpy_array[:,0]
#1. ve 2. sütun
first_and_second_column = numpy_array[:,0:2]
print(first_column)
print(first_and_second_column)

[0 2 4 6 8]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#Dizinin herhangi bir elemanını seçmek
selecting_item = numpy_array[3,1]
print(selecting_item)

7


In [ ]:
numpy_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
print(numpy_array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
print(numpy_array[::-1])

[[8 9]
 [6 7]
 [4 5]
 [2 3]
 [0 1]]


In [ ]:
#belirtilen satir ve sutunda zero matris olusturur
print(np.zeros((5,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:

#verilen olculerde birlik matris olusturur
print(np.ones((3,3,3)))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
#verilen olculerde birim matris olusturur
#4X4 lük birim matris
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
#Satır bazlı birleştirme
print(np.concatenate([numpy_array, numpy_array], axis =0))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]
 [0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
#Sütun bazlı birleştirme
print(np.concatenate([numpy_array, numpy_array], axis =1))

[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]
 [6 7 6 7]
 [8 9 8 9]]


In [ ]:
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
print(numpy_array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
print(numpy_array.max())

9


In [ ]:
print(numpy_array.min())

0


In [ ]:
#Satırların toplamı
print(numpy_array.sum(axis = 1))

[ 1  5  9 13 17]


In [ ]:
#Sütunların toplamı
print(numpy_array.sum(axis = 0))

[20 25]


In [ ]:
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
print(numpy_array.mean())

4.5


In [ ]:
print(np.median(numpy_array))

4.5


In [ ]:
print(numpy_array.var())


8.25


In [ ]:
print(numpy_array.std()

In [ ]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(3,3)
#dizimizi 3x3 lük, 2 boyutlu bir matrise dönüştürdük.
print(numpy_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(numpy_array + numpy_array)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
print(numpy_array - numpy_array)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
print(numpy_array * numpy_array)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [ ]:
print(numpy_array + 5)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
print(numpy_array * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [ ]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(3,3)
#dizimizi 3x3 lük, 2 boyutlu bir matrise dönüştürdük.
print(np.sin(numpy_array))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]
 [ 0.6569866   0.98935825  0.41211849]]


In [ ]:
print(np.cos(numpy_array))

[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]
 [ 0.75390225 -0.14550003 -0.91113026]]


In [ ]:
print(np.sqrt(numpy_array)) 

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [ ]:
print(np.exp(numpy_array))

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]


In [ ]:
print(np.log(numpy_array))

[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [ ]:
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array1 = numpy_array.reshape(5,2)
numpy_array2 = numpy_array.reshape(2,5)
print(np.dot(numpy_array1,numpy_array2))

[[  5   6   7   8   9]
 [ 15  20  25  30  35]
 [ 25  34  43  52  61]
 [ 35  48  61  74  87]
 [ 45  62  79  96 113]]


In [ ]:
#matrisin transpozu
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
numpy_array = numpy_array.reshape(5,2)
print(numpy_array)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [ ]:
print(numpy_array.T) 

[[0 2 4 6 8]
 [1 3 5 7 9]]


In [ ]:
numpy_array = np.array([0,1, 2, 3, 4, 5, 6, 7, 8, 9])
boolean_array = numpy_array >= 5
print(boolean_array)

[False False False False False  True  True  True  True  True]


In [ ]:
# 5 ve 5'ten büyük elemanlar
print(numpy_array[boolean_array])

# 5 ten küçük elemanlar
print(numpy_array<5)
print(numpy_array[numpy_array<5])

[5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[0 1 2 3 4]
